### PR TITLE
Optimised code

### PR DESCRIPTION
**Pull request by RudideC**
had to do it
will do this for other files later

### CODE REVIEW

**Comment by EpiclyRaspberry** [comment]
bro removed every sexually transmitted diseases ever

**Comment by RudideC** [comment]
all right, time to optimise the rest

**Comment by RudideC** [comment]
this pr has to be accepted so that I can make a new one :( 👎

**Comment by FloppyDolphin57** [comment]
> this pr has to be accepted so that I can make a new one :( 👎

no one will accept this pr because it is bad.

**Comment by notchyves** [comment]
not optimized buddy its just yucky

**Comment by RudideC** [comment]
dude, typing std:: one million times is ugly asf

**Comment by FloppyDolphin57** [comment]
> dude, typing std:: one million times is ugly asf

No it's not. Using namespace std is bad practice and any good code will not have that.

**Comment by Hzqkii** [comment]
> dude, typing std:: one million times is ugly asf

`using namespace std;` is bad practice, and doesn't "optimize" the program in anyway.
refer to: [learncpp.com/cpp-tutorial/cpp-faq/#usingnamespace](https://www.learncpp.com/cpp-tutorial/cpp-faq/#usingnamespace)

**Comment by aShanki** [comment]
Denied, since it's useless.

**Pull request closed without merging**
