### PR TITLE
gapple counter omg

### PR DESCRIPTION
**Pull request by PoopyHaters**
omg omg omg omg omg omg

### CODE REVIEW

**Comment by PoopyHaters** [comment]
(not copied from arrow counter)

**Comment by PoopyHaters** [comment]
100%

**Comment by treegfx** [comment]
ur nuking manager LMFAOOO
i suggest pulling before committing

**Comment by PoopyHaters** [comment]
nuking manager
wot

**Comment by PoopyHaters** [comment]
uh what did i nuke

**Comment by PoopyHaters** [comment]
lemme remake it

**Comment by treegfx** [comment]
look at #updates in the discord

**Comment by treegfx** [comment]
https://discord.com/channels/1049946152092586054/1059875297807310960

**Comment by PoopyHaters** [comment]
im banned

**Comment by PoopyHaters** [comment]
bro forgot 💀

**Comment by treegfx** [comment]
no ur not

**Comment by treegfx** [comment]
ur back since like a month LMFAO

**Comment by PoopyHaters** [comment]
no

**Comment by PoopyHaters** [comment]
im not

**Comment by PoopyHaters** [comment]
i will ban evade XD

**Comment by treegfx** [comment]
what

**Comment by PoopyHaters** [comment]
for fralier

**Comment by PoopyHaters** [comment]
i retired from being a bot anyway

**Comment by treegfx** [comment]
whats your discord username again

**Comment by PoopyHaters** [comment]
how do i pull

**Comment by PoopyHaters** [comment]
its @kdarkadas

**Comment by PoopyHaters** [comment]
i use github website idk what git is

**Comment by PoopyHaters** [comment]
tell them to unban

**Comment by treegfx** [comment]
i did bruh 
be fucking patient
also how tf do you not know git?????
dont you have the repo locally

**Comment by PoopyHaters** [comment]
idk

**Pull request closed without merging**
