### PR TITLE
Initial 1.20.60 update

### PR DESCRIPTION
**Pull request by marioCST**

### CODE REVIEW

**Comment by marioCST** [comment]
Tested, didn't have any crashes that haven't been there for months

**Comment by FreezeEngine** [comment]
> Tested, didn't have any crashes that haven't been there for months

Actor::getRenderPositionComponent() 4C 8B 41 48 41 BB 1C 58 40 E9
Actor::getMoveInputHandler() 40 53 48 83 EC 20 48 8B ? ? 2E
Actor::getActorHeadRotationComponent() 4C 8B ? ? 41 BB 6E F3 E8 D4
LocalPlayer* getLocalPlayer() vfunc index likely wrong
RakPeer vtable likely wrong

Broken modules: keystrokes, ping counter, auto sprint

**Comment by FreezeEngine** [comment]
> Tested, didn't have any crashes that haven't been there for months

Actor::getRenderPositionComponent() 4C 8B 41 48 41 BB 1C 58 40 E9
Actor::getMoveInputHandler() 40 53 48 83 EC 20 48 8B ? ? 2E
Actor::getActorHeadRotationComponent() 4C 8B ? ? 41 BB 6E F3 E8 D4
LocalPlayer* getLocalPlayer() vfunc index likely wrong
RakPeer vtable likely wrong

Broken modules: keystrokes, ping counter, auto sprint

**Comment by marioCST** [comment]
Fixed

**Comment by marioCST** [comment]
> > Tested, didn't have any crashes that haven't been there for months
> 
> Actor::getRenderPositionComponent() 4C 8B 41 48 41 BB 1C 540 53 48 83 EC 20 48 8B ? ? 2E8 40 E9 Actor::getMoveInputHandler() Actor::getActorHeadRotationComponent() 4C 8B ? ? 41 BB 6E F3 E8 D4 RakPeer vtable likely wrong
> 
> Broken modules: keystrokes, ping counter, auto sprint

as a side note: all the component sigs are wrong. the RenderPositionComponent sig isnt even valid

**Comment by FreezeEngine** [comment]
> > > Tested, didn't have any crashes that haven't been there for months
> 
> > 
> 
> > Actor::getRenderPositionComponent() 4C 8B 41 48 41 BB 1C 540 53 48 83 EC 20 48 8B ? ? 2E8 40 E9 Actor::getMoveInputHandler()
> 
> Actor::getActorHeadRotationComponent() 4C 8B ? ? 41 BB 6E F3 E8 D4 RakPeer vtable likely wrong
> 
> > 
> 
> > Broken modules: keystrokes, ping counter, auto sprint
> 
> 
> 
> as a side note: all the component sigs are wrong. the RenderPositionComponent sig isnt even valid

Hitboxes worked with this :D What I did was find .50 sig in .50 server, copy function name, find it in .60 server, sig it and test in ce and in flarial :о

**Comment by marioCST** [comment]
Inefficient, you don't need the whole .50 part

**Comment by FreezeEngine** [comment]
> Inefficient, you don't need the whole .50 part

Well, I didnt know how to get them and what it was at the time so had to compare. Looked it up recenly and as far as I know part of the sig is component type hash. Im a little new to this but Ill try my best 👍

**Comment by marioCST** [comment]
Closing due to 1.20.70 update

**Pull request closed without merging**
